version: '3'
services:
  backend:
    image: me/backend
    build:
      context: backend
    volumes:
      - ./backend/public:/usr/src/app/public
    env_file:
      - secrets.env
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/usr/share/nginx/html:ro
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
